const FEATURE_KEY = 'COMPARE_PRODUCT :: ';
const SET_FEATURE_LIST = FEATURE_KEY + 'SET_FEATURE_LIST';
const SET_PRODUCT_TITLES = FEATURE_KEY + 'SET_PRODUCT_TITLES';
const SET_PRODUCT_IMAGES = FEATURE_KEY + 'SET_PRODUCT_IMAGES';
const SET_PRODUCT_PRICING_SUMMARY = FEATURE_KEY + 'SET_PRODUCT_PRICING_SUMMARY';

export default Object.freeze({
    SET_FEATURE_LIST,
    SET_PRODUCT_TITLES,
    SET_PRODUCT_IMAGES,
    SET_PRODUCT_PRICING_SUMMARY
});